# Generated by Django 2.2.7 on 2019-11-20 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seelk_hacking_game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='seelk_alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=100)),
                ('down_limit', models.DecimalField(decimal_places=4, max_digits=12)),
                ('up_limit', models.DecimalField(decimal_places=4, max_digits=12)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seelk_hacking_game.seelk_user')),
            ],
        ),
    ]
