# Generated by Django 2.2.7 on 2019-11-20 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seelk_hacking_game', '0002_seelk_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seelk_alert',
            name='user_email',
        ),
    ]
