# Generated by Django 2.2.7 on 2019-11-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seelk_hacking_game', '0003_remove_seelk_alert_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='seelk_alert',
            name='alert_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='seelk_alert',
            name='alert_name',
            field=models.CharField(default='Alert', max_length=100),
        ),
    ]
