# Generated by Django 2.2.7 on 2019-11-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seelk_hacking_game', '0004_auto_20191120_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seelk_alert',
            old_name='down_limit',
            new_name='alert_param',
        ),
        migrations.RemoveField(
            model_name='seelk_alert',
            name='up_limit',
        ),
        migrations.AddField(
            model_name='seelk_alert',
            name='alert_mov',
            field=models.CharField(choices=[('b', 'Both'), ('u', 'Up'), ('d', 'Down')], default='b', max_length=10),
        ),
    ]
