# Generated by Django 2.2.7 on 2019-11-26 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seelk_hacking_game', '0006_btc_last_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seelk_alert',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='seelk_user',
        ),
    ]
